dependencies:
  - OpenZeppelin/openzeppelin-contractsa@4.1.0
compiler:
   solc:
   remappings: 
    - "@openzeppelin=OpenZeppelin/openzeppelin-contractsa@4.1.0"
dotenv: .env
wallets:
   from_key: ${PRIVATE_KEY}